### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by hansoogithub** [song-qun/HyperNetwork#1]
thank you for the project, 
im using ubuntu 22.04.3 LTS
after creating a conda enviroment, i installed pip==20.2.4 and installed based on the requirements.txt
but i have installation issues in the following, please advise

Collecting numpy==1.19.0
  Using cached numpy-1.19.0.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /home/hanz/anaconda3/envs/hypernet/bin/python /home/hanz/anaconda3/envs/hypernet/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpzvh370zx
         cwd: /tmp/pip-install-zxykq4d2/numpy
    Complete output (63 lines):
    Running from numpy source directory.
    <string>:460: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
    /tmp/pip-install-zxykq4d2/numpy/tools/cythonize.py:73: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      required_version = LooseVersion('0.29.14')
    /tmp/pip-install-zxykq4d2/numpy/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      if LooseVersion(cython_version) < required_version:
    performance hint: _generator.pyx:706:41: Exception check will always require the GIL to be acquired. Possible solutions:
    	1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
    	2. Use an 'int' return type on the function to allow an error code to be returned.
    performance hint: _generator.pyx:735:45: Exception check will always require the GIL to be acquired. Possible solutions:
    	1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
    	2. Use an 'int' return type on the function to allow an error code to be returned.
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        def __init__(self, seed=None):
            BitGenerator.__init__(self, seed)
            self.rng_state.pcg_state = &self.pcg64_random_state
    
            self._bitgen.state = <void *>&self.rng_state
            self._bitgen.next_uint64 = &pcg64_uint64
                                       ^
    ------------------------------------------------------------
    
    _pcg64.pyx:113:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'uint64_t (void *) except? -1 nogil'.
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/mtrand.pyx
    Processing numpy/random/bit_generator.pyx
    Processing numpy/random/_generator.pyx
    Processing numpy/random/_pcg64.pyx
    Traceback (most recent call last):
      File "/tmp/pip-install-zxykq4d2/numpy/tools/cythonize.py", line 235, in <module>
        main()
      File "/tmp/pip-install-zxykq4d2/numpy/tools/cythonize.py", line 231, in main
        find_process_files(root_dir)
      File "/tmp/pip-install-zxykq4d2/numpy/tools/cythonize.py", line 222, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/tmp/pip-install-zxykq4d2/numpy/tools/cythonize.py", line 188, in process
        processor_function(fromfile, tofile)
      File "/tmp/pip-install-zxykq4d2/numpy/tools/cythonize.py", line 77, in process_pyx
        subprocess.check_call(
      File "/home/hanz/anaconda3/envs/hypernet/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/hanz/anaconda3/envs/hypernet/bin/python', '-m', 'cython', '-3', '--fast-fail', '-o', '_pcg64.c', '_pcg64.pyx']' returned non-zero exit status 1.
    Cythonizing sources
    Traceback (most recent call last):
      File "/home/hanz/anaconda3/envs/hypernet/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/home/hanz/anaconda3/envs/hypernet/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/hanz/anaconda3/envs/hypernet/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-37ncr41g/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 396, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-37ncr41g/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 507, in run_setup
        super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
      File "/tmp/pip-build-env-37ncr41g/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
        exec(code, locals())
      File "<string>", line 489, in <module>
      File "<string>", line 469, in setup_package
      File "<string>", line 274, in generate_cython
    RuntimeError: Running cythonize failed!
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/hanz/anaconda3/envs/hypernet/bin/python /home/hanz/anaconda3/envs/hypernet/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpzvh370zx Check the logs for full command output.

**Comment by song-qun** [comment]
This error is caused by a mismatch between cython and numpy versions. Could you try to upgrade numpy or downgrade cython?
